### ISSUE TITLE
Dynamic Partition create not correct

### ISSUE THREAD

**Issue by zhangboya1** [apache/incubator-doris#5803] opened 2021-05-13 03:17 UTC
I create a table with properties
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-30",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "3",
"dynamic_partition.buckets" = "12",
"storage_medium" = "SSD",
"storage_format" = "V2"
);

When new partition created, the storage_medium is HDD, not SSD. 
Why? Is it a bug?

**Comment by hf200012** [comment] 2021-05-14 05:24
How is your SSD disk mounted, and how is the name of the doris storage directory named?
The directory names of your configured doris storage directories hdd and ssd should be similar to doris.SSD, doris.HDD

storage_root_path = /hdd_data05/doris.HDD;/ssd_data03/doris.SSD;/hdd_data08/doris.HDD;/hdd_data02/doris.HDD;/hdd_data04/doris.HDD;/hdd_data01/doris.HDD;/hdd_data10/doris.HDD; ;/ssd_data02/doris.SSD;/hdd_data09/doris.HDD;/hdd_data06/doris.HDD;/hdd_data03/doris.HDD;/ssd_data01/doris.SSD;/hdd_data07/doris.HDD;/ssd_data04/doris.SSD

**Comment by hf200012** [comment] 2021-05-14 05:25
> I create a table with properties
> PROPERTIES (
> "replication_num" = "3",
> "dynamic_partition.enable" = "true",
> "dynamic_partition.time_unit" = "DAY",
> "dynamic_partition.time_zone" = "Asia/Shanghai",
> "dynamic_partition.start" = "-30",
> "dynamic_partition.end" = "3",
> "dynamic_partition.prefix" = "p",
> "dynamic_partition.replication_num" = "3",
> "dynamic_partition.buckets" = "12",
> "storage_medium" = "SSD",
> "storage_format" = "V2"
> );
> 
> When new partition created, the storage_medium is HDD, not SSD.
> Why? Is it a bug?

This is your configuration problem, not a bug

**Comment by zhangboya1** [comment] 2021-05-14 08:19
my configuration is:
storage_root_path = /data01/doris.SSD,2000;/data02/doris.SSD,2000;/data03/doris.SSD,2000;/data04/doris.SSD,2000

**Comment by morningman** [comment] 2021-05-14 08:21
> My configuration is:
> storage_root_path = /data01/doris.SSD,2000;/data02/doris.SSD,2000;/data03/doris.SSD,2000;/data04/doris.SSD,2000

This is a issue. Currently, dynamic partition does not consider the `storage_medium` property, this should be fixed later.

**Comment by zhangboya1** [comment] 2021-05-14 08:29
Got it. I have read the code, in the analyzeDataProperty method, the properties not contain storage_medium . For now I create partition manually.

**Closed** 2021-05-18 08:19 UTC
