### ISSUE TITLE
[BUG] The metric http restful API has problem

### ISSUE THREAD

**Issue by zhangboya1** [apache/incubator-doris#6363] opened 2021-08-03 02:21 UTC
In document fe-metrics, it shows "You can get Json format by visiting http://fe_host:fe_http_port/metrics?type=json".
But I got prometheus format response with the url. 
I read code in httpv2/rest/MetricsAction.java, I found json format returned when type equals 'agent', not 'json'.
In http/rest/MetricsAction.java, I found json format returned when type equals 'json'.
So I guess it's a bug.

**Comment by hf200012** [comment] 2021-08-03 02:32
This is not a bug. When the type parameter is json, json data is returned

http://10.220.146.10:8030/metrics?type=json

`[
  {
    "tags": {
      "metric": "jvm_heap_size_bytes",
      "type": "max"
    },
    "unit": "nounit",
    "value": 4181590016
  },
  {
    "tags": {
      "metric": "jvm_heap_size_bytes",
      "type": "committed"
    },
    "unit": "nounit",
    "value": 2181017600
  },
  {
    "tags": {
      "metric": "jvm_heap_size_bytes",
      "type": "used"
    },
    "unit": "nounit",
    "value": 1346978752
  },
  ......
  ,{
    "tags": {
      "metric": "node_info",
      "status": "is_master"
    },
    "unit": "nounit",
    "value": 1
  }
]`

**Closed** 2021-08-09 02:27 UTC
