### ISSUE TITLE
[Bug] Routine loads don't consume kafka topic

### ISSUE THREAD

**Issue by fanlongmengjd** [apache/incubator-doris#3370] opened 2020-04-21 19:27 UTC
**Describe the bug**
Routine load was running but didn't consume
1.  Be.INFO showed the frequency of routine load task scheduled to Be was less.
![image](https://user-images.githubusercontent.com/63618584/79904800-1f4d1800-83ca-11ea-8b5e-3e3c712753cb.png) 
07:42->07:43-07:51->08:04->08:39
2. There was "running" transactions which status were committed and got stuck , didn't change
![image](https://user-images.githubusercontent.com/63618584/79905027-794ddd80-83ca-11ea-8d5c-c53e926d9609.png)
drill down and find 
![image](https://user-images.githubusercontent.com/63618584/79905437-1f99e300-83cb-11ea-9b0c-90f22f12e049.png)
check the tablet 
![image](https://user-images.githubusercontent.com/63618584/79905478-2cb6d200-83cb-11ea-8733-4687ad093683.png)

3. There were some warning in fe.warn.log
![image](https://user-images.githubusercontent.com/63618584/79905549-47894680-83cb-11ea-90d4-40f2ffa223f6.png)

**To Reproduce**

**Expected behavior**
Consume properly

 - OS: CentOS
 - Browser chrome
 - Version 0.11.33.1

**Work around**

1. pause routine loads 
2. restart fe master
the committed transactions, got stuck, disappeared 
3. resume routine loads
the message in fe.warn.log  disappeared
routine load work properly

**Comment by morningman** [comment] 2020-04-26 14:32
I can't see the image you post in issue.
Did you see some rollback failure log? If yes, it seems that the scheduler process has something wrong, you can upgrade to 0.11.42 to see if the problem is fixed.
We've make some bug fixed in new version.

**Comment by morningman** [comment] 2020-04-26 14:38
Oh I see, we talked in WeChat group. It seems DROPPING PARTITION may cause this problem. You can try to pause the process of dropping partition and see if this problem could happen again.

**Comment by fanlongmengjd** [comment] 2020-05-02 18:05
yes, sounds like that.
I use :admin set frontend   config("catalog_trash_expire_second" = "60") to workaround this problem, but i don't know the root cause
--

**Comment by fanlongmengjd** [comment] 2020-05-08 01:21
this issue showed again. 
i checked fe.log, fe.warn, fe.audit, there was not any drop action.
but issue happened again.
![image](https://user-images.githubusercontent.com/63618584/81360004-838cfe80-908f-11ea-90c3-c475e6ad12ee.png)

**Comment by fanlongmengjd** [comment] 2020-05-08 01:23
this time admin set frontend config("catalog_trash_expire_second" = "5")

**Closed** 2022-04-25 10:59 UTC
Labels: kind/fix
